name: github.io

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: setup
        uses: actions/configure-pages@v5
      - name: magic.html
        run: echo -e "<html>\n<body><p>$(date)</p></body>" >>magic.html
      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
